---
galaxy_info:
  role_name: system_tuning
  namespace: ariel99gf
  author: "Ariel Fonseca"
  description: "DevOps & SRE kernel performance tuning and security hardening"
  company: "Personal"
  license: "MIT"
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - system
    - performance
    - security
    - sysctl
    - devops
    - sre

dependencies: []
