# ==============================================================================
# distrobox.ini - SRE / DevOps / Platform Engineering Sandbox
# Managed by Ansible / Distrobox Assemble
# ==============================================================================
[sre-toolbox]
image=registry.fedoraproject.org/fedora-toolbox:44
pull=true
start_now=true
init=false
nvidia=true
volume="/run/user/1000/podman/podman.sock:/var/run/docker.sock:rw"
init_hooks="/var/home/agfonseca/Projects/dotfiles/distrobox/provision-sre.sh"
